### ISSUE TITLE
As a user, I want to create an account.

### ISSUE THREAD

**Issue by Hamna-Akh** [Polaroid-Soen-341/SOEN341#10]
- When I come to website there is a button to create an account
- When creating account all my information (name,email) will be taken
- When creating an account I will create a secure password
- Once created only to access my account is with the set user name and password
- after creating account there is a button to be able to login from the homepage
- after creating an account and logging in is a button to log out on every page.

**Comment by JackieDan** [comment]
Everything was tested. Closing issue.

**Comment by Hamna-Akh** [comment]
Acceptance Test: Testing user registration.
Priority: High
Steps:
1. Click on register button
2. Enter first name
3. Enter last name
4. Enter valid email address
5. Enter username
6. Enter valid password (8 characters)
7. Confirm password (must match)
8. Click submit button

**Comment by Hamna-Akh** [comment]
<img width="446" alt="AT#1" src="https://user-images.githubusercontent.com/77466360/114637615-cbe96f00-9c97-11eb-8af1-9a7a8c77cc33.png">
