### ISSUE TITLE
As a user, I want to login.

### ISSUE THREAD

**Issue by Hamna-Akh** [Polaroid-Soen-341/SOEN341#11]
As a user I want to login to their account using a username and password.

-need users models
-need user authentication #20

**Comment by NathanFortier** [comment]
implemented pushed to develop, closing issue.

**Comment by Hamna-Akh** [comment]
Acceptance Test: Testing login
Priority: High
Steps:
1. Enter username
2. Enter password
3. Click login button

Expected result: Log in

**Comment by Hamna-Akh** [comment]
<img width="624" alt="AT#2" src="https://user-images.githubusercontent.com/77466360/114637787-28e52500-9c98-11eb-9d74-46097cec0526.png">
