### ISSUE TITLE
Bug Conflicting dependencies for djangorestframework-jwt

### ISSUE THREAD

**Issue by NathanFortier** [Polaroid-Soen-341/SOEN341#41]
The conflict is caused by:
    The user requested PyJWT==2.0.1
    djangorestframework-jwt 1.11.0 depends on PyJWT<2.0.0 and >=1.5.2

Need to change requirements.txt to aleviate this conflict. This was found by travis, see travis implementation branches build.
https://travis-ci.com/github/Polaroid-Soen-341/SOEN341/builds/218454943

**Comment by JackieDan** [comment]
Issue was solved by modifying the requirements.txt file with the good versions.
